### ISSUE TITLE
How can I download the code?

### ISSUE THREAD

**Issue by smolendawid** [Startup-Landing/Startup-Landing#10]
I'd like to download the React code of one of the landing pages. Sorry for a newbie question but I have no idea how to do that.

**Comment by TeshaneCrawford** [comment]
Hey, you could either download the code via git clone by going to one of the Startup Landing git repositories or you could use an easy option by visiting this side of theirs, https://startuplanding.redq.io/ 
All of the demo websites are available in Nextjs and gatsby and a figma file with the design

**Comment by smolendawid** [comment]
Ok, somehow I didn't notice the repos on Startup Landing account. Thanks!
