### ISSUE TITLE
SVG Logo

### ISSUE THREAD

**Issue by erobus** [Startup-Landing/Startup-Landing#2]
How to change svg logo? I have tried with creating a svg logo in illustrator changing src/assets/logo-dark.svg didn't work. Logo simply didn't load in page. Talking about agency creative next.js template.

**Comment by paulruet** [comment]
Hi,
If you want to change the site logo, your logo must be in (src/assets/) folder.
**First way**: your logo must have svg format. then your logo name change (logo-dark.svg ).
**Second way:**  Your logo may have format (jpg, png, svg) . Open this (header.js) file your code editor and edit line 10 (logo-dark.svg to your logo name with extension ( logo.png))
header.js file location ->->-> **templates/011-agency-creative/011-agency-creative-next/src/components/header/header.js**
