### ISSUE TITLE
Best practice to integrate with Sanity.io?

### ISSUE THREAD

**Issue by Molnfront** [Startup-Landing/Startup-Landing#5]
How would one go about to fetch content from Sanity the best way without to many API calls? 

I see that the different sections is in functions and then used in pages/index.js so maybe you could do a fetch in index and then query an array for the different content types.

**Comment by paulruet** [comment]
Okay, you guess it right. Do a fetch request from `pages/index.js` and then you have two options, pass your data via props or use Context API to show them in different components as you want.

**Comment by Molnfront** [comment]
Thnks!
